# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
jobs:
- job: Job_1
  displayName: Agentless job
  condition: succeeded()
  pool: server
  steps:
  - task: Delay@1
    displayName: 'Delay by 1 minutes'
    inputs:
      delayForMinutes: 1
- job: Phase_1
  displayName: Phase 1
  condition: succeeded()
  pool:
    vmImage: Hosted VS2017
  steps:
  - powershell:
    displayName: 'PowerShell Script'