# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Phase_1
  displayName: CloudBuild Phase
  condition: succeeded()
  pool: server
  steps:
  - task: Delay@1
    displayName: 'Delay by 1 minutes'
    inputs:
      delayForMinutes: 1
- job: Job_1
  displayName: Docker Phase
  dependsOn: Phase_1
  condition: succeeded()
  pool:
    vmImage: win1803
  steps:
  - powershell:
    displayName: 'PowerShell Script'
- job: Phase_2
  displayName: CloudTest Phase
  dependsOn: Phase_1
  condition: and(succeeded(), eq(variables['CloudTest.Enabled'], 'true'))
  pool: server
  steps:
  - task: Delay@1
    displayName: 'Delay by 1 minutes'
    inputs:
      delayForMinutes: 1
