# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: DeployDev  

  variables:
    - group: Test
    - group: AllowedBranchesPerEnvironment

  steps:
  - script: "echo $(test)"
  - script: "echo $(branch_Ring0)"
